### ISSUE TITLE
Performance Degradation Due to Iterating Over Array Without useMemo in React Component

### ISSUE THREAD

**Issue by MhammdAli** [kamel404/ecommerce-react#1]
Iterating over an array inside a React component without using useMemo can cause significant performance issues. This occurs because the iteration and any calculations performed are re-executed on every render, even if the data hasn't changed. This is particularly problematic with larger arrays or components that re-render frequently, leading to unnecessary computational overhead and a slower user experience

**Bad Code Example:**

```
state.map((item) => {
  return (subtotal += item.price * item.qty);
});
```

**Solution:**
To avoid unnecessary recalculations and improve performance, wrap the array iteration and calculation in a useMemo hook. This ensures that the computation only runs when the state array changes.

**Refactored Code Example:**
```
const subtotal = useMemo(() => {
  return state.reduce((total, item) => total + item.price * item.qty, 0);
}, [state]);
```

**Comment by kamel404** [comment]
Fixed the Cart Component 
used useMemo to memoize the subtotal, totalItems, and total calculations
