### ISSUE TITLE
Performance and Complexity Issues Due to Declaring a Component Inside Another Component in React

### ISSUE THREAD

**Issue by MhammdAli** [kamel404/ecommerce-react#2]
**Problem:**
Declaring a component inside another component in React can cause several issues:

    1. Re-Creation on Every Render: The inner component is re-created every time the outer component re-renders. This leads to a performance hit because the inner component and all its effects and states are re-initialized on every render, even if there are no changes.
    
    2. Increased Complexity: Embedding components inside other components can make the code more difficult to understand and 
maintain. It becomes challenging to track which components are being re-created and why, increasing the likelihood of bugs and maintenance difficulties.

**Bad Code Example:**

```
function OuterComponent() {
  function InnerComponent() {
    return <div>Inner Component</div>;
  }

  return <InnerComponent />;
}
```

**Solution:**
To avoid these issues, always declare components at the top level, outside of any other components. This prevents unnecessary re-creations and keeps the code cleaner and easier to manage.

**Refactored Code Example:**

```
function InnerComponent() {
  return <div>Inner Component</div>;
}

function OuterComponent() {
  return <InnerComponent />;
}
```

**Comment by kamel404** [comment]
Solved, made each subcomponent a component then use it in the origanal component
